CONSTANTS.MODES.REP = 'Rep';
CONSTANTS.MODES.NONREP = 'NonRep';

CONSTANTS.PHASES.PREPROCESSING = 1;
CONSTANTS.PHASES.FIRINGRATE = 2;
CONSTANTS.PHASES.STASTC = 3;
CONSTANTS.PHASES.LINEARFILTER = 4;
CONSTANTS.PHASES.GENERATOR = 5;
