function [fitresult, gof] = createFitGideon(generator, rate)
%CREATEFIT2(GENERATOR,RATE)
%  Create a fit.
%
%  Data for 'fit 1' fit:
%      X Input : generator
%      Y Output: rate
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Feb-2013 12:01:37


%% Fit: 'fit 1'.
[xData, yData] = prepareCurveData( generator, rate );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf];
opts.StartPoint = [-3.49340264065553e-15 32.5689102549367 3.49340264065547e-15 32.5689102549367];
opts.Upper = [Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'rate vs. generator', 'fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'generator' );
ylabel( 'rate' );
grid on


