function [fitresult, gof] = FitLNmodel(X, Y,cell)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Feb-2015 14:52:52


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'a/(1+exp(-k*(x-b)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.157613081677548 0.970592781760616 0.957166948242946];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( cell+10 );
figure;
h = plot( fitresult, xData, yData );hold on
legend( h, 'Y vs. X', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'X' );
ylabel( 'Y' );
title({['Cell num. ' num2str(cell)];['a=' num2str(fitresult.a) ...
    '  b=' num2str(fitresult.b) '  k=' num2str(fitresult.k)];['R^2=' num2str(gof.rsquare)]});
% text(-1,3,['a=' num2str(fitresult.a)],'FontSize',18)
% text(-1,3,['b=' num2str(fitresult.b)])
% text(-1,3,['k=' num2str(fitresult.k)])
% text(-1,3,['R^2=' num2str(gof.rsquare)])
% 
grid on


