function [fitresult, gof] = createFit(funcXData, funcYMeans, ...
    iNeuron, MODE)
%CREATEFIT(FUNCXDATA,FUNCYMEANS)
%  Create a fit.
%
%  Data for 'Interpolant Linear Fit' fit:
%      X Input : funcXData
%      Y Output: funcYMeans
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Feb-2015 03:29:43


%% Fit: 'Interpolant Linear Fit'.
[xData, yData] = prepareCurveData( funcXData, funcYMeans );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
h = plot( fitresult, xData, yData );
legend( h, 'After Linear Filter vs. Rate', ...
    sprintf('Interpolant Linear Fit (%s)', MODE), 'Location', 'NorthEast');

% Label axes
xlabel( 'After Linear Filter' );
ylabel( 'Rate' );

title(sprintf('Neuron #%d', iNeuron));
grid on


