function [fitresult, gof] = createFit(funcXData, funcYMeans, ...
    iNeuron, MODE)
%CREATEFIT(FUNCXDATA,FUNCYMEANS)
%  Create a fit.
%
%  Data for 'Interpolant Linear Fit' fit:
%      X Input : funcXData
%      Y Output: funcYMeans
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Feb-2015 03:29:43


%% Fit: 'Interpolant Linear Fit'.
[xData, yData] = prepareCurveData( funcXData, funcYMeans );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', sprintf('Interpolant Linear Fit (%s)', MODE));
h = plot( fitresult, xData, yData );
legend( h, 'After Linear Filter vs. Raw', 'Interpolant Linear Fit', 'Location', 'NorthEast' );
% Label axes
xlabel( 'After Linear Filter' );
ylabel( 'Raw' );

title(sprintf('Neuron #%d', iNeuron));
grid on


